name: CMake

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Install Conan and Ninja
      run: pip install conan ninja
    
    - name: Run the test script
      run: test/build.ps1
      shell: pwsh

    - name: Archive Conan Output
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: Conan Output
        path: ${{github.workspace}}/build/conan/